services:
  postgres:
    # command: -c log_statement=all
    shm_size: 256m
    image: postgres:16
    restart: unless-stopped
    ports:
    - 127.0.0.1:5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
